spring:
  application:
    name: bloodbank-service
  profiles:
    active: local

server:
  port: 6688

cron:
  expression: "0 0 00 * * *"

logging:
  file: ./log/bloodBankService.log
  level:
    org.springframework.data.mongodb.core.MongoTemplate: ERROR
    ca.uhn.fhir.parser.LenientErrorHandler : ERROR
    
donor:
  autogenarator-code: DNR
  autogenarator-startno: 1001

donorVisit:
  autogenarator-code: DNR-V
  autogenarator-startno: 1001


